my_first_job:
  cron: "*/30 * * * * *" #it will retrieve data every 1 minute
  class: "UpdateDbWorker"

# my_first_job:
#   cron: "*/1 * * * *" #it will retrieve data every 1 minute
#   class: "SayHelloWorker"
